#!/usr/bin/python -u
#
import sys
import socket
import time
import datetime
import select
import json

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

MSG_SIZE = 1500
TIMEOUT = 60

# Bind to localhost and an ephemeral port
UDP_IP = "127.0.0.1"
UDP_PORT = int(sys.argv[1])

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
UDP_PORT = sock.getsockname()[1]
log("[bound] " + str(UDP_PORT))

def perform_exit():
  for key in sorted(finalPackets.keys()):
    sys.stdout.write(finalPackets[key]['data'])
  log("[completed]")
  sys.exit(0)

#Set a buffer to hold our packets
finalPackets = {}  # 250: packet, 500: packet
#Set the expected sequence we should be at
expectedSequence = 0

# Now listen for packets
while True:
  log("Starting RECV Loop")
  canRecv = select.select([sock], [], [], 5)
  log("READY: " + str(canRecv))
  if canRecv[0]:
    result = sock.recvfrom(MSG_SIZE)
    # If nothing is ready, we hit the timeout
    if result:
      (data, addr) = result
      try:

        decoded = json.loads(data)

        # If the EOF flag is set and we are at the expected sequence
        # which in this case should be the last sequence then exit
        if (decoded['eof']):
          log("Performing Exit: Got a True EOF")
          perform_exit()

        # If there is data, we accept it and print it out
        if decoded['data']:
          # If we receive data, we assume it's in-order
          # You will need to do much more here
          log("[recv data] " + str(decoded['sequence']) + " (" + str(len(decoded['data'])) + ") ACCEPTED (in-order)")
          # If our buffer does not have the current sequence data add it to the buffer
          if not finalPackets.has_key(decoded['sequence']):
            finalPackets[decoded['sequence']] = decoded

          if decoded['sequence'] == expectedSequence:
            expectedSequence += len(decoded['data'])
            finalPackets[decoded['sequence']] = decoded

        # Send back an ack to the sender
        msg = json.dumps({"ack": decoded['sequence'] + len(decoded['data']), 'timestamp': time.time(), 'eof': False})
        if sock.sendto(msg, addr) < len(msg):
          log("[error] unable to fully send packet")
        else:
          log("[ACK SENT] This is the ack: " + msg)


      except (ValueError, KeyError, TypeError) as e:
        log("[recv corrupt packet] RECV SIDE")
        raise e
    else:
      log("[error] timeout RECV SIDE")
      sys.exit(-1)